### ISSUE TITLE
Document 0.1.0/0.2.0 additions...

### ISSUE THREAD

**Issue by hairyhenderson** [hairyhenderson/node-fellowshipone#16]
A bunch of stuff was added/changed in 0.1.0 and 0.2.0. This should be at least vaguely covered in the `README.md`

**Comment by ingageco** [comment]
Can you add a simple usage area in the readme? Can't seem to put 2+2 together to see how to make a call after successfully authenticating. My intention is to contribute to expanding the routes once I figure it out.

**Comment by hairyhenderson** [comment]
Hi @ingageco! Thanks so much for the interest - imagine my surprise that others actually want to use this! :grin:

I'll try to put something useful into the `README` over the next few days.

Also, I would _totally_ appreciate any contributions you could make! :smile:

Merry Christmas! :christmas_tree:

**Comment by ingageco** [comment]
Ha @hairyhenderson - I understand the surprise, being fairly new to github. It looks great so far, and it looks like one of the first projects I can grasp enough to contribute to. 

My main issue was that if i did f1.authenticate in my server.js, afterwards I could not make a call with f1 when it was passed to a route. This my be just my own ignorance of node & JS in general, and I didn't try the other option (get_token). So i ended up hard-coding the token / secret (not sure if i'm supposed to) and now I can pass f1 around to routes it seems. Just chalk it up to me being a noob.

Merry Christmas to you as well!
