### ISSUE TITLE
Adjust config API url

### ISSUE THREAD

**Issue by ingageco** [hairyhenderson/node-fellowshipone#33]
The api URL in the config (at least in the example) ends in /v1. This will need to be changed to go into the giving realm specifically where the api URL becomes /giving/v1 - so current configuration is limiting. Will send a PR if I find a good solution.

**Comment by ingageco** [comment]
Maybe each realm could have a prefix - people would just be '/v1' (appended to the API url) - but giving would be '/giving/v1', groups '/groups/v1', and so on.

**Comment by hairyhenderson** [comment]
Ah. I guess this is from the (relatively) new giving and groups realm updates...

I'm thinking the `apiURL` config item should probably be changed to be just the bare scheme and FQDN (so, `https://mychurch.staging.fellowshipone.com`). Then - as you say - each resource type would get a prefix starting with `/v1` (or something else as appropriate)...

This would be a breaking change, but there's really only one other project (that I know of!) that uses this library (https://github.com/hairyhenderson/f1foo), so it's easy to update.

**Comment by ingageco** [comment]
@hairyhenderson I adjusted it in my project - removed /v1 from the API url, then just added it to the indivdual routes. I've successfully added contribution receipts as a module. Expect a fork and PR soon for you to review.

**Comment by hairyhenderson** [comment]
Ok. :+1: a PR would be great :)

**Comment by hairyhenderson** [comment]
@ingageco - were you going to submit a PR for this? Or should I?
