### ISSUE TITLE
Households.show - nothing returned

### ISSUE THREAD

**Issue by ingageco** [hairyhenderson/node-fellowshipone#57]
Hey @hairyhenderson - I'm back working on this project for the short-term, and I'm having some issues with calling the show method on Households. Here's my code:

```
        var households = new F1.Households(f1);


        households.show( 363073379 , function (err, found) {
        var count = found.results['@count']
        console.log('Found %d households', count)
        if (count > 0) {
          console.log('Households: %j', found.results.household)
        }

        res.send("done");

      })
```

Here's my households.js file: 

```
'use strict';

var util = require('util')
var _ = require('lodash')
var request = require('request')
var async = require('async')
var F1Resource = require('./f1resource')

function Households(f1) {
  F1Resource.call(this, f1, {
    resourceName: 'household',
    path: '/v1/households'
  })
}

util.inherits(Households, F1Resource)

module.exports = Households
```

What am I doing wrong? I keep getting 404 errors. Thanks man!

**Comment by ingageco** [comment]
Tried to do people.list as a workaround and i'm getting undefined on the body in the callback on every request. Any help?

**Comment by hairyhenderson** [comment]
Hi @ingageco - sorry about this! Seems a little odd. I've been using `Households.create` without issue.

What version of the module are you using? The current `households.js` (https://github.com/hairyhenderson/node-fellowshipone/blob/master/lib/households.js) in `master` (or version 0.3.3) doesn't have the `path: '/v1/households'` line in it - that could be causing a 404...

**Comment by ingageco** [comment]
I'm using your newest version now. I added the path because of the experience I was having. Even without the path I still get 404/undefined returned every time on the Household.show() method.

**Comment by hairyhenderson** [comment]
Sorry about the radio silence... Been pretty busy lately 😞 

So, just to be clear - you're getting 404s _only_ on `Households.show()`? Or do you get a 404 on `Households.list()` too, for example...

The only part of the Households API I use in the wild is actually just `Households.create()` so it could be that `show()` is busted. Not sure why that would be though... It's been a while that I've actually connected  to the live F1 API, so it'll take a bit of effort to dig my keys up etc. Will try to have a look over the next few days.

**Comment by ingageco** [comment]
I don't think F1 had a method for Households.list() when I looked. I can try that!

**Comment by hairyhenderson** [comment]
Assuming this was solved - closing. Go ahead and re-open if there's still an issue.
